version: 2.1

jobs:
  pre_commit:
    docker:
      - image: cimg/python:3.9.1
    steps:
      - checkout
      - run: pip3 install pre-commit
      - run: pre-commit run --all-files --verbose
  docker_build:
    docker:
      - image: cimg/python:3.9.1
    steps:
      - checkout
      - run: docker build .

workflows:
  main_test:
    jobs:
      - pre_commit
      - docker_build
